[package]
name = "ix-files"
version.workspace = true
edition.workspace = true

[dependencies]
ix-core = { path = "../ix-core" }
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
bytes = "1"
walkdir = "2"
regex = "1"
glob = "0.3"

[dev-dependencies]
tempfile.workspace = true
criterion.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }

[[bench]]
name = "files_bench"
harness = false
